# Generated by Django 4.1.7 on 2023-02-19 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_aboutme"),
    ]

    operations = [
        migrations.CreateModel(
            name="MyProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="Project Image")),
                ("description", models.TextField()),
                ("title", models.CharField(max_length=200)),
            ],
        ),
    ]
