# Generated by Django 4.1.7 on 2023-03-04 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_skills"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactMe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(max_length=200)),
                ("mes", models.TextField()),
                ("sen", models.EmailField(max_length=254)),
                ("rec", models.EmailField(max_length=254)),
                ("created", models.DateTimeField()),
            ],
        ),
    ]
