# Generated by Django 4.1.7 on 2023-03-08 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_delete_contactme"),
    ]

    operations = [
        migrations.AddField(
            model_name="work",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
