# Generated by Django 4.1.7 on 2023-03-08 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_work_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="work",
            name="description",
            field=models.TextField(),
        ),
    ]
