# Generated by Django 4.1.7 on 2023-03-08 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_alter_work_description"),
    ]

    operations = [
        migrations.RenameField(
            model_name="work",
            old_name="description",
            new_name="work",
        ),
    ]
